/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Application {
  /**
   * The name of the template the app is using
   */
  template: string;
  /**
   * A property bag that fills in the values for the chosen template
   */
  values: {
    [k: string]: string | number;
  };
}
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ControlPlaneConfiguration =
  | ApplicationAssignment
  | ApplicationDeployment
  | Cluster
  | ApplicationTemplate;

export interface ApplicationAssignment {
  kind: 'ApplicationAssignment';
  metadata: {
    /**
     * The name of the assignment
     */
    name: string;
  };
  spec: {
    /**
     * The name of the ApplicationDeployment
     */
    application: string;
    /**
     * The name of the Cluster
     */
    cluster: string;
  };
}
export interface ApplicationDeployment {
  kind: 'ApplicationDeployment';
  metadata: {
    /**
     * The name of the application deployment
     */
    name: string;
  };
  spec: {
    /**
     * The url to a Git repository where the Application (app.yaml) is located
     */
    repo: string;
    /**
     * The Git ref (branch/tag/commit) to use
     */
    ref: string;
    /**
     * The path within the repo to the Application (app.yaml) file
     */
    path: string;
    /**
     * The number of clusters to deploy to, or 'all' for all clusters that match the selector
     */
    clusters: number | 'all';
    /**
     * Create assignments on clusters with label keys and values matching this selector. If empty or not present, the deployment is assumed to target any registered Cluster
     */
    selector?: {
      [k: string]: string;
    };
  };
}
export interface Cluster {
  kind: 'Cluster';
  metadata: {
    /**
     * The name of the cluster
     */
    name: string;
    /**
     * Map of string keys and values that can be used to organize and categorize (scope and select) objects
     */
    labels?: {
      [k: string]: string;
    };
  };
  spec: {
    /**
     * One or more environments to which the cluster belongs
     */
    environments?: string[];
  };
}
export interface ApplicationTemplate {
  kind: 'ApplicationTemplate';
  metadata: {
    /**
     * The name of the template, which will be used by Applications
     */
    name: string;
  };
  spec: {
    /**
     * The url to a Git repository where the Template definition is located
     */
    repo: string;
    /**
     * The Git ref (branch/tag/commit) to use
     */
    ref: string;
    /**
     * The path within the repo to the Template definition file
     */
    path: string;
  };
}
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Template {
  /**
   * Relative path to a folder that contains k8s manifests
   */
  manifests: string;
  /**
   * A property bag that defines what properties are available to set on this template
   */
  parameters: {
    [k: string]: {
      default?: string | number;
    };
  };
}
